# -*- coding: utf-8 -*-
"""98-acc-dr-detection-with-xai-in-three-models (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19o8CWljPcEG0mwV5aqJ1VaNUnTQ1XL-I

# ****Binary Classification of Diabetic Retinopathy Using EfficientNetB3****
"""

from tensorflow import lite
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import pandas as pd
import random, os
import shutil
import matplotlib.pyplot as plt
from matplotlib.image import imread
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.metrics import categorical_accuracy
from sklearn.model_selection import train_test_split

# Add an additional column, mapping to the type
df = pd.read_csv(r'../input/diabetic-retinopathy-224x224-gaussian-filtered/train.csv')

diagnosis_dict_binary = {
    0: 'No_DR',
    1: 'DR',
    2: 'DR',
    3: 'DR',
    4: 'DR'
}

diagnosis_dict = {
    0: 'No_DR',
    1: 'Mild',
    2: 'Moderate',
    3: 'Severe',
    4: 'Proliferate_DR',
}


df['binary_type'] =  df['diagnosis'].map(diagnosis_dict_binary.get)
df['type'] = df['diagnosis'].map(diagnosis_dict.get)
df.head()

print(df.info())

print(df.describe())

print(df.isnull().sum())

print(df.duplicated().sum())

# إعدادات الشكل العام للرسم البياني
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (12, 6)

# توزيع الأنواع الخمسة لـ DR
plt.figure(figsize=(10,6))
sns.countplot(y='type', data=df, order=df['type'].value_counts().index, palette='viridis')
plt.title('Distribution of Diabetic Retinopathy Types', fontsize=16)
plt.xlabel('Number of Images')
plt.ylabel('Diagnosis Type')
plt.show()

plt.figure(figsize=(10,5))
df['diagnosis'].value_counts().sort_index().plot(kind='bar', color='skyblue', edgecolor='black')
plt.title('Distribution of Original Diagnosis Labels')
plt.xlabel('Diagnosis Class (0-4)')
plt.ylabel('Count')
plt.grid(axis='y')
plt.show()

plt.figure(figsize=(8,4))
sns.countplot(y='binary_type', data=df, order=df['binary_type'].value_counts().index, palette='plasma')
plt.title('Binary Classification Distribution (No_DR vs DR)', fontsize=14)
plt.xlabel('Number of Images')
plt.ylabel('Binary Type')
plt.show()



type_distribution = df['type'].value_counts(normalize=True) * 100
binary_distribution = df['binary_type'].value_counts(normalize=True) * 100

print("Class Distribution (Percentage):")
print(type_distribution.round(2))

print("\nBinary Class Distribution (Percentage):")
print(binary_distribution.round(2))

plt.figure(figsize=(8, 5))
sns.heatmap(pd.crosstab(df['type'], df['binary_type']), annot=True, fmt='d', cmap='YlGnBu')
plt.title('Cross-tab Heatmap between Full Diagnosis and Binary Class')
plt.ylabel('Full Diagnosis')
plt.xlabel('Binary Class')
plt.show()

df['type'].value_counts().plot(kind='barh')

df['binary_type'].value_counts().plot(kind='barh')

import random
from matplotlib.image import imread

diagnosis_classes = df['type'].unique()
src_dir = r'../input/diabetic-retinopathy-224x224-gaussian-filtered/gaussian_filtered_images/gaussian_filtered_images'

plt.figure(figsize=(15, 10))
for idx, diag in enumerate(diagnosis_classes):
    sample = df[df['type'] == diag].sample(1)
    img_id = sample['id_code'].values[0] + ".png"
    img_path = os.path.join(src_dir, diag, img_id)

    img = imread(img_path)

    plt.subplot(2, 3, idx+1)
    plt.imshow(img, cmap='gray')
    plt.title(f"{diag}")
    plt.axis('off')

plt.suptitle('Sample Images from Each Class', fontsize=18)
plt.tight_layout()
plt.show()

import cv2
import numpy as np

def compute_brightness(image_path):
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is not None:
        return np.mean(img)
    else:
        print(f"Image not found or unreadable: {image_path}")
        return None

brightness_vals = []

for idx, row in df.iterrows():
    diag = row['type']
    img_id = row['id_code'] + ".png"
    img_path = os.path.join(src_dir, diag, img_id)
    brightness = compute_brightness(img_path)
    if brightness is not None:
        brightness_vals.append(brightness)
brightness_vals = np.array(brightness_vals)


print("Brightness statistics over all images:")
print(f"Mean brightness: {brightness_vals.mean():.2f}")
print(f"Standard deviation: {brightness_vals.std():.2f}")
print(f"Minimum brightness: {brightness_vals.min():.2f}")
print(f"Maximum brightness: {brightness_vals.max():.2f}")

plt.figure(figsize=(8,5))
sns.histplot(brightness_vals, bins=50, color='orange')
plt.title('Brightness Distribution of All Images')
plt.xlabel('Mean Brightness')
plt.ylabel('Frequency')
plt.show()

# Split into stratified train, val, and test sets
train_intermediate, val = train_test_split(df, test_size = 0.15, stratify = df['type'])
train, test = train_test_split(train_intermediate, test_size = 0.15 / (1 - 0.15), stratify = train_intermediate['type'])

print(train['type'].value_counts(), '\n')
print(test['type'].value_counts(), '\n')
print(val['type'].value_counts(), '\n')

# Class distribution in train, val, test sets
fig, axs = plt.subplots(1, 3, figsize=(20, 6))
sns.countplot(data=train, y='type', order=train['type'].value_counts().index, ax=axs[0], palette='cool')
axs[0].set_title('Train Set Distribution')

sns.countplot(data=val, y='type', order=val['type'].value_counts().index, ax=axs[1], palette='cubehelix')
axs[1].set_title('Validation Set Distribution')

sns.countplot(data=test, y='type', order=test['type'].value_counts().index, ax=axs[2], palette='mako')
axs[2].set_title('Test Set Distribution')

plt.tight_layout()
plt.show()

# Binary class distribution across sets
fig, axs = plt.subplots(1, 3, figsize=(20, 5))

sns.countplot(data=train, x='binary_type', ax=axs[0], palette='Set2')
axs[0].set_title('Train Set - Binary Distribution')

sns.countplot(data=val, x='binary_type', ax=axs[1], palette='Set2')
axs[1].set_title('Validation Set - Binary Distribution')

sns.countplot(data=test, x='binary_type', ax=axs[2], palette='Set2')
axs[2].set_title('Test Set - Binary Distribution')

plt.tight_layout()
plt.show()

# Create working directories for train/val/test
base_dir = ''

train_dir = os.path.join(base_dir, 'train')
val_dir = os.path.join(base_dir, 'val')
test_dir = os.path.join(base_dir, 'test')

if os.path.exists(base_dir):
    shutil.rmtree(base_dir)

if os.path.exists(train_dir):
    shutil.rmtree(train_dir)
os.makedirs(train_dir)

if os.path.exists(val_dir):
    shutil.rmtree(val_dir)
os.makedirs(val_dir)

if os.path.exists(test_dir):
    shutil.rmtree(test_dir)
os.makedirs(test_dir)

# Copy images to respective working directory
src_dir = r'../input/diabetic-retinopathy-224x224-gaussian-filtered/gaussian_filtered_images/gaussian_filtered_images'
for index, row in train.iterrows():
    diagnosis = row['type']
    binary_diagnosis = row['binary_type']
    id_code = row['id_code'] + ".png"
    srcfile = os.path.join(src_dir, diagnosis, id_code)
    dstfile = os.path.join(train_dir, binary_diagnosis)
    os.makedirs(dstfile, exist_ok = True)
    shutil.copy(srcfile, dstfile)

for index, row in val.iterrows():
    diagnosis = row['type']
    binary_diagnosis = row['binary_type']
    id_code = row['id_code'] + ".png"
    srcfile = os.path.join(src_dir, diagnosis, id_code)
    dstfile = os.path.join(val_dir, binary_diagnosis)
    os.makedirs(dstfile, exist_ok = True)
    shutil.copy(srcfile, dstfile)

for index, row in test.iterrows():
    diagnosis = row['type']
    binary_diagnosis = row['binary_type']
    id_code = row['id_code'] + ".png"
    srcfile = os.path.join(src_dir, diagnosis, id_code)
    dstfile = os.path.join(test_dir, binary_diagnosis)
    os.makedirs(dstfile, exist_ok = True)
    shutil.copy(srcfile, dstfile)

from tensorflow.keras.applications import EfficientNetB3
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.models import Model
from tensorflow.keras import layers, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import os
from tensorflow.keras.metrics import AUC

# Paths
train_path = 'train'
val_path = 'val'
test_path = 'test'

# Data Augmentation + Preprocessing
train_gen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=15,
    zoom_range=0.2,
    shear_range=0.2,
    horizontal_flip=True,
    # brightness_range=[0.7, 1.3],
    width_shift_range=0.1,
    height_shift_range=0.1
)

val_gen = ImageDataGenerator(preprocessing_function=preprocess_input)
test_gen = ImageDataGenerator(preprocessing_function=preprocess_input)

train_batches = train_gen.flow_from_directory(train_path, target_size=(300,300), batch_size=32, class_mode='binary')
val_batches = val_gen.flow_from_directory(val_path, target_size=(300,300), batch_size=32, class_mode='binary')
test_batches = test_gen.flow_from_directory(test_path, target_size=(300,300), batch_size=32, class_mode='binary', shuffle=False)

"""## ****1. Building an EfficientNetB3 Model on Gaussian Filtered 224x224 Images****

### Model Construction and Initial Training

We build a convolutional neural network using EfficientNetB3 as the base model with pretrained ImageNet weights.  
The base model is frozen to retain learned features while training a custom classifier head with dense and dropout layers for binary classification.  
The model is compiled with Adam optimizer, binary cross-entropy loss, and evaluation metrics including accuracy and AUC for robust performance measurement.  
Training proceeds for 10 epochs with early stopping and learning rate reduction callbacks to prevent overfitting and optimize convergence.
"""

# Build Model
base_model = EfficientNetB3(include_top=False, input_shape=(300,300,3), pooling='avg', weights='imagenet')
base_model.trainable = False

x = base_model.output
x = layers.Dense(128, activation='relu')(x)
x = layers.Dropout(0.4)(x)
output = layers.Dense(1, activation='sigmoid')(x)

model = Model(inputs=base_model.input, outputs=output)

# Compile
model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy',AUC(name='auc')]
)

# Callbacks
early_stop = EarlyStopping(patience=3, restore_best_weights=True)
lr_scheduler = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, verbose=1)

# Initial training
history = model.fit(
    train_batches,
    epochs=10,
    validation_data=val_batches,
    callbacks=[early_stop, lr_scheduler]
)

# Fine-Tuning
base_model.trainable = True

# Freeze أول 100 طبقة
for layer in base_model.layers[:50]:
    layer.trainable = False

model.compile(
    optimizer=optimizers.Adam(1e-5),
    loss='binary_crossentropy',
    metrics=['accuracy' , AUC(name='auc')]
)

history_finetune = model.fit(
    train_batches,
    epochs=10,
    validation_data=val_batches,
    callbacks=[early_stop, lr_scheduler]
)

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

y_pred_prob = model.predict(test_batches).ravel()
y_true = test_batches.classes

fpr, tpr, thresholds = roc_curve(y_true, y_pred_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.3f})')
plt.plot([0,1], [0,1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0,1.0])
plt.ylim([0.0,1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC)')
plt.legend(loc='lower right')
plt.show()

import matplotlib.pyplot as plt

# Use history_finetune to plot Fine-Tuning performance
# To plot initial training instead, replace history_finetune with history
# You can also combine both to show the entire training process

# Loss plot
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)  # 1 row, 2 columns, first plot
plt.plot(history_finetune.history['loss'], label='Training Loss')
plt.plot(history_finetune.history['val_loss'], label='Validation Loss')
plt.title('Loss Over Epochs (Fine-Tuning)')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# Accuracy plot
plt.subplot(1, 2, 2)  # 1 row, 2 columns, second plot
plt.plot(history_finetune.history['accuracy'], label='Training Accuracy')
plt.plot(history_finetune.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy Over Epochs (Fine-Tuning)')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""## **Model Evaluation at Varying Thresholds**"""

from sklearn.metrics import classification_report

# Ensure the test_batches are reset before prediction
test_batches.reset()
predictions_proba = model.predict(test_batches)

# True labels
y_true = test_batches.classes

# Class names: Ensure index 0 is 'DR' and 1 is 'No_DR'
class_names = ['DR', 'No_DR']

print("\n--- Model Evaluation at Different Thresholds ---")

# Try a range of thresholds from 0.10 to 0.95
thresholds = np.arange(0.1, 1.0, 0.05)

best_f1_dr = -1
best_threshold = -1

for threshold in thresholds:
    y_pred_binary = (predictions_proba > threshold).astype(int)

    # Generate classification report
    report = classification_report(y_true, y_pred_binary, target_names=class_names, output_dict=True)

    print(f"\n--- Threshold: {threshold:.2f} ---")
    print(f"Accuracy: {report['accuracy']:.4f}")
    print(f"  DR - Precision: {report['DR']['precision']:.4f}, Recall: {report['DR']['recall']:.4f}, F1-score: {report['DR']['f1-score']:.4f}")
    print(f"  No_DR - Precision: {report['No_DR']['precision']:.4f}, Recall: {report['No_DR']['recall']:.4f}, F1-score: {report['No_DR']['f1-score']:.4f}")

    # Find the best F1-score for the DR class
    if report['No_DR']['f1-score'] > best_f1_dr:
        best_f1_dr = report['No_DR']['f1-score']
        best_threshold = threshold

print(f"\n--- Best Threshold (based on F1-score for No_DR): {best_threshold:.2f} (F1-score: {best_f1_dr:.4f}) ---")

"""## ****3. Evulate Model on Aptos 2019 Dataset****"""

import pandas as pd
import numpy as np
import cv2
import os
import shutil
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import load_model  # For loading a trained model

# Base path to the new APTOS-2019 dataset
new_data_base_path = '/kaggle/input/aptos2019/'
new_csv_file = os.path.join(new_data_base_path, 'train_1.csv')  # Using train_1.csv as requested

new_images_dir = os.path.join(new_data_base_path, 'train_images/train_images/')

# Load the CSV file
df_new = pd.read_csv(new_csv_file)

df_new['id_code'] = df_new['id_code'].astype(str) + '.png'
# Define a dictionary for binary classification mapping
diagnosis_dict_binary = {
    0: 'No_DR',
    1: 'DR',
    2: 'DR',
    3: 'DR',
    4: 'DR'
}

# Add a binary classification column based on the diagnosis mapping
df_new['binary_type'] = df_new['diagnosis'].map(diagnosis_dict_binary.get)

print("Info about the new dataset:")
print(df_new.head())
print("\nDistribution of binary classes in the new dataset:")
print(df_new['binary_type'].value_counts())

# Base directory of the original images
image_base_dir = new_images_dir  # e.g., '/kaggle/input/aptos2019/train_images/train_images/'

# Original classes (0 to 4)
original_classes = [0, 1, 2, 3, 4]

plt.figure(figsize=(15, 6))

for i, cls in enumerate(original_classes):
    # Filter dataframe for the current class
    sample_df = df_new[df_new['diagnosis'] == cls]
    if sample_df.empty:
        print(f"No images found for class {cls}")
        continue

    # Randomly select one image ID from the class
    sample_img_id = random.choice(sample_df['id_code'].values)
    img_path = os.path.join(image_base_dir, sample_img_id)

    # Read and convert the image to RGB
    img = cv2.imread(img_path)
    if img is not None:
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        plt.subplot(1, len(original_classes), i + 1)
        plt.imshow(img_rgb)
        plt.title(f"Class: {cls}")
        plt.axis('off')
    else:
        print(f"Image not found or cannot be read: {img_path}")

plt.tight_layout()
plt.show()

from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

# Split the new data (df_new) into train/validation/test sets
# Use stratified splitting to maintain class balance
train_intermediate_new, val_new_df = train_test_split(
    df_new, test_size=0.15, stratify=df_new['binary_type'], random_state=42)

train_new_df, test_new_df = train_test_split(
    train_intermediate_new, test_size=0.15/(1-0.15), stratify=train_intermediate_new['binary_type'], random_state=42)

print("\nBinary class distribution in the new training set:")
print(train_new_df['binary_type'].value_counts())
print("\nBinary class distribution in the new validation set:")
print(val_new_df['binary_type'].value_counts())
print("\nBinary class distribution in the new test set (for model evaluation):")
print(test_new_df['binary_type'].value_counts())

# Plot class distributions in the new splits
fig, axs = plt.subplots(1, 3, figsize=(20, 5))

sns.countplot(data=train_new_df, x='binary_type', ax=axs[0], palette='Set2')
axs[0].set_title('Train Set New Data - Binary Distribution')

sns.countplot(data=val_new_df, x='binary_type', ax=axs[1], palette='Set2')
axs[1].set_title('Validation Set New Data - Binary Distribution')

sns.countplot(data=test_new_df, x='binary_type', ax=axs[2], palette='Set2')
axs[2].set_title('Test Set New Data - Binary Distribution')

plt.tight_layout()
plt.show()

def preprocess_aptos_image_for_eval(image_base_dir, target_size=(300, 300)):
    """
    Preprocess APTOS image for evaluation: read, resize to target size, and convert to RGB.
    """
    img = cv2.imread(image_base_dir)
    if img is None:
        return None

    img_resized = cv2.resize(img, target_size)

    if len(img_resized.shape) == 2:
        img_resized = cv2.cvtColor(img_resized, cv2.COLOR_GRAY2RGB)
    elif img_resized.shape[2] == 4:
        img_resized = cv2.cvtColor(img_resized, cv2.COLOR_BGRA2BGR)

    return img_resized

processed_test_images_dir = 'processed_new_test_images_for_eval'

if os.path.exists(processed_test_images_dir):
    shutil.rmtree(processed_test_images_dir)

os.makedirs(os.path.join(processed_test_images_dir, 'No_DR'), exist_ok=True)
os.makedirs(os.path.join(processed_test_images_dir, 'DR'), exist_ok=True)

print("Processing and copying new test set images...")
processed_image_paths = []
processed_labels = []

for index, row in test_new_df.iterrows():
    img_id = row['id_code']
    original_img_path = os.path.join(new_images_dir, img_id)

    if not os.path.exists(original_img_path):
        continue

    processed_img = preprocess_aptos_image_for_eval(original_img_path, target_size=(300, 300))

    if processed_img is not None:
        binary_label = row['binary_type']
        output_folder = os.path.join(processed_test_images_dir, binary_label)
        output_path = os.path.join(output_folder, img_id)
        cv2.imwrite(output_path, processed_img)

        processed_image_paths.append(output_path)
        processed_labels.append(binary_label)

print(f"Processed {len(processed_image_paths)} images from the new test set.")

processed_test_df_eval = pd.DataFrame({
    'filepath': processed_image_paths,
    'class': processed_labels
})

print(processed_test_images_dir)

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt


test_gen_for_eval = ImageDataGenerator(preprocessing_function=preprocess_input)

# Use flow_from_dataframe to ensure alignment between images and labels
test_batches_for_eval = test_gen_for_eval.flow_from_dataframe(
    dataframe=processed_test_df_eval,
    x_col='filepath',
    y_col='class',
    target_size=(300, 300),
    batch_size=32,
    class_mode='binary',
    shuffle=False  # Important to keep predictions and true labels aligned
)

# --- Evaluate the model on the new processed APTOS-2019 test set ---
print("\nEvaluating model on new processed APTOS-2019 test set...")
evaluation_results = model.evaluate(test_batches_for_eval)

print("\n--- Model performance on new processed APTOS-2019 test set: ---")
for name, value in zip(model.metrics_names, evaluation_results):
    print(f"{name}: {value:.4f}")
print("---")

"""## ***Find the best Thresholds by Confusion Matrix and Classification Report at Threshold***"""

from sklearn.metrics import classification_report

# Reset generator and get predictions
test_batches_for_eval.reset()
predictions = model.predict(test_batches_for_eval)
y_true = test_batches_for_eval.classes
class_names = list(test_batches_for_eval.class_indices.keys())

# Thresholds to compare
thresholds = [0.3, 0.65]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for i, thresh in enumerate(thresholds):
    y_pred_binary = (predictions > thresh).astype(int)
    cm = confusion_matrix(y_true, y_pred_binary)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names,
                ax=axes[i])
    axes[i].set_title(f'Confusion Matrix at Threshold {thresh}')
    axes[i].set_xlabel('Predicted Label')
    axes[i].set_ylabel('True Label')

    print(f"\n--- Classification Report at Threshold {thresh} ---")
    print(classification_report(y_true, y_pred_binary, target_names=class_names))

plt.tight_layout()
plt.show()

fpr, tpr, thresholds = roc_curve(y_true, predictions)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()

model.save('CNN.model')

loss, acc, auc = model.evaluate(test_batches, verbose=1)
print("Loss:", loss)
print("Accuracy:", acc)
print("AUC:", auc)

"""# ****Model Predicting DR from Different Image****"""

new_model = tf.keras.models.load_model("CNN.model")

def predict_class(path):
    # 1. Read the image
    img = cv2.imread(path)
    if img is None:
        print(f"Error: Could not find or read image from path: {path}")
        return

    # 2. Resize the image and convert to RGB
    img_resized = cv2.resize(img, (300, 300))
    img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)

    # Display the input image
    plt.imshow(img_rgb)
    plt.title(f"Input Image: {os.path.basename(path)}")
    plt.axis('off')
    plt.show()

    image = preprocess_input(img_rgb.astype('float32'))
    image = np.expand_dims(image, axis=0)

    raw_prediction_output = new_model.predict(image)[0][0] # Image of a neural network prediction

    per = np.argmax(np.array([[raw_prediction_output, 1 - raw_prediction_output]]), axis=1)

    # Print the predicted class based on your original logic
    if per == 0:
        print('No DR')
    else:
        print('DR')

    # Print the probability for each class
    print(f"Probability (No DR): {raw_prediction_output:.4f}")
    print(f"Probability (DR): {1 - raw_prediction_output:.4f}")

predict_class('../input/diabetic-retinopathy-224x224-gaussian-filtered/gaussian_filtered_images/gaussian_filtered_images/Severe/0104b032c141.png')
predict_class('../input/diabetic-retinopathy-224x224-gaussian-filtered/gaussian_filtered_images/gaussian_filtered_images/Moderate/000c1434d8d7.png')
predict_class('../input/diabetic-retinopathy-224x224-gaussian-filtered/gaussian_filtered_images/gaussian_filtered_images/No_DR/002c21358ce6.png')

predict_class('../input/aptos2019/test_images/test_images/e4f12411fd85.png') # DR
predict_class('../input/aptos2019/test_images/test_images/e50b0174690d.png')#  No DR
predict_class('../input/aptos2019/test_images/test_images/e632e38fd2d4.png') # No DR